"""Index long url

Revision ID: d02d21754393
Revises: 9bf5e6026d04
Create Date: 2025-07-09 02:47:17.805450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02d21754393'
down_revision: Union[str, Sequence[str], None] = '9bf5e6026d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_long_url', 'urls', ['long_url'], unique=False)
    op.create_index(op.f('ix_urls_long_url'), 'urls', ['long_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_long_url'), table_name='urls')
    op.drop_index('ix_long_url', table_name='urls')
    # ### end Alembic commands ###
